### ISSUE TITLE
TODO when breaking compatibility

### ISSUE THREAD

**Issue by f-f** [spacchetti/spago#94]
The goal of this issue is to list all the things that we might want to do the next time we are going to break compatibility (probably when 1.0 will happen). The reason for this is that bundling breaking changes is always a good thing to do, since people will have to make changes anyways, and it's best to just do it once than to repeatedly have to do it.

Up to date list of things we might want to do:
- [x] ~rename `packages.dhall` to `package-set.dhall`: the name `packages` is confusing because we have to explain it contains the package-set~ update: the ship for this has probably sailed, as now spacchetti has merged into package-sets, so everything is just called `packages`, so let's keep it like that for consistency
- [x] stop publishing under `purescript-spago` on NPM, and only publish under `spago`: the fact that we publish both might be confusing
- [x] ~start failing when package-sets don't include the minimum compiler version~ update: this cannot be done by design, as package sets might come from a hash as well. All we can do then is to log a warning "spago assumes that you know what you're doing since we cannot parse the version from the package-set tag"
